apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: communication-service
  namespace: s652
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: communication-service
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75